routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('produtos', 'ProdutoController')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('reservas', 'ReservaController');

Route::post('pesquisa', 'ReservaController@pesquisa')->name('reserva.pesquisa');

Route::get('dadosReservas', 'ProdutoController@dadosReservas')->name('produtos.dadosReservas');

Route::get('graficos', 'ProdutoController@graficos')->name('produtos.graficos');

Route::get('relatorios', 'ProdutoController@relatorios')->name('produtos.relatorios');

Route::get('res_email/{id}', 'ProdutoController@email')->name('produtos.email')->middleware('auth');

Route::resource('reservasapi', 'ReservaApiController', ['except'=>['create', 'edit']]);

resources/views/acha_instru.blade.php
@extends('principal')
@section('pagina')

@if (session('status'))
<div class="alert alert-success">
  {{ session('status') }}
</div>
@endif
<div>
  <h3>Instrumentos encontrados</h3>
</div>


<div>
  @foreach ($reg as $linha)
    
  <div class="row">
    <div class="col-sm-6">
      <a href="{{ route('reservas.show', $linha->id) }}">
      <img src='storage/{{ $linha->foto }}' alt="foto" style='width: 400px; height: 300px;' ></a>

      <p>
        -------------------------------------------------------------------------------------
      </p>
    
    </div>
    <div class="col-sm-6">
      <h4>
       Modelo: {{$linha->modelo}}
      </h4>
      <h4>
       Marca: {{$linha->marca}}
      </h4>
    </div>
  </div>


@endforeach
</div>

@endsection

resources/views/cad_reserva.blade.php
@extends('principal') 
@section('pagina') 


@if (session('status'))
<div class="alert alert-success">
    {{ session('status') }}
</div>
@endif

@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif


    <h3>Cadastro para reserva</h3>
    

        <div class="row">
            <div class="col-sm-6">
                <img src='../../storage/{{ $reg->foto }}' alt="Foto" style='width: 300px; height: 200px;' >
            </div>
            <div class="col-sm-6">
                <p>
                    Modelo: {{$reg->modelo}}
                </p>
                <p>
                    Marca: {{$reg->marca}}
                </p>
            </div>

        </div>

        <h4>Informe seus dados para concluir a Reserva</h4>
        
        <form method="post" action="{{ route('reservas.store') }}" enctype="multipart/form-data">

       
            {{ csrf_field() }}
            <div class="row">
                <div class="col-sm-8">
                    <div class="form-group">
                        <label for="nome">Nome:</label>
                        <input type="text" class="form-control" id="nomeCliente" name="nomeCliente" autofocus
                        >

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-8">
                    <div class="form-group">
                        <label for="email">Email:</label>
                        <input type="email" class="form-control" id="emailCliente" name="emailCliente">

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-8">
                    <div class="form-group">
                        <label for="email">Tel.Celular:</label>
                        <input type="text" class="form-control" id="telefone" name="telefone">

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-8">
                    <div class="form-group">
                        <label for="email">Data Desejada:</label>
                        <input type="text" class="form-control" id="data" name="data">

                    </div>
                </div>
            </div>
            <input type="hidden" id='produto_id' name='produto_id' value='{{$reg->id}}'>
            <div class="row">
                <div class="col-sm-8">
                    <input type="submit" value="Reservar" class="btn btn-danger" style="margin:10px">
                </div>
            </div>
        </form>

{{-- @endsection

@section('js') --}}
  <script src="https://code.jquery.com/jquery-latest.min.js"></script>
  <script src="{{ URL::asset('js/jquery.mask.min.js') }}"></script>

  <script>
    $(document).ready(function() {
        $('#data').mask('00/00/0000');
    });
  </script>  
@endsection

resources/views/dados_reservas.blade.php
@extends('modelo') 
@section('conteudo')

<div class="row">
  <div class="col-sm-12">
     <h3>Reservas Feitas</h3>
  </div>     
</div>

@if (session('status'))
<div class="alert alert-success">
  {{ session('status') }}
</div>
@endif

<table class="table table-hover">
  <thead>
    <tr>
      <th>C.R.</th>
      <th>Nome</th>
      <th>Email</th>
      <th>Tel.Celular</th>
      <th>Data Desejada</th>
      <th>C.I.</th>
      <th>Instrumento Reservado</th>
      <th>Envio de confirmação por email</th>
    </tr>
  </thead>
  <tbody>

    @foreach ($linhas as $linha)
    <tr>
      <td> {{ $linha->id }} </td>
      <td> {{ $linha->nomeCliente }} </td>
      <td> {{ $linha->emailCliente }} </td>
      <td> {{ $linha->telefone }} </td>
      <td> {{ $linha->data }} </td>
      <td> {{ $linha->produto_id }} </td>
      <td> {{ $linha->modelo }}, {{$linha->categoria}}, {{$linha->marca}} </td>
      <td> 
          <a href="{{ route('produtos.email', $linha->id) }}" class="btn btn-primary btn-sm" role="button">Enviar</a>&nbsp;


      </td>
    </tr>
    
    @endforeach

  </tbody>
</table>

{{-- {{ $linhas->links() }} --}}
  
 
@endsection

resources/views/email_reserva.blade.php
<h1>Conheça, teste, aprove antes de comprar!! </h1>
<h3>Olá {{$reserva->nomeCliente}}!</h3>
<h3>Confirmamos sua reserva do instrumento</h3>
<h4>Agora voçê ter a experência de tocar em um instrumento de alta qualidade.</h4>
<h4>Foi uma decisão muito inteligente</h4>
<h4>Obrigado e aproveite.</h4>

resources/views/exibiinstrumentos.blade.php
@extends('principal')
@section('pagina')

@if (session('status'))
<div class="alert alert-success">
  {{ session('status') }}
</div>
@endif

<tbody>

    <div class="row">
        <div class="col-sm-12">
            <p>
              Clique para fazer na foto para fazer a reserva
            </p>
        </div>
    </div>

@foreach ($linhas as $linha)
    
    
        <div class="col-md-4">
          <div class="thumbnail" >
            <a href='{{ route('reservas.show', $linha->id) }}'>
              <img src='storage/{{ $linha->foto }}' alt="Foto" style='width: 300px; height: 200px;'></a>
              <div class="caption">
                <p>
                  <b>Marca --</b>  {{$linha->marca}} 
                </p>
              </div>
            
          </div>
        </div>
    



@endforeach

</tbody>

@endsection

resources/views/form_produtos.blade.php
@extends('modelo')

 @section('conteudo') 
 
 @if ($acao == 1)
<h3>Inclusão de Instrumentos</h3>
<form method="post" action="{{ route('produtos.store') }}" enctype="multipart/form-data">

  @elseif ($acao == 2)
  <h3>Altualizção de Instrumentos</h3>
  <form method="post" action="{{ route('produtos.update', $reg->id) }}" enctype="multipart/form-data">
    {{ method_field('put') }} @else
    <h3>Consulta de Instrumentos</h3>

    @endif {{ csrf_field() }}

    <div class="row">
        <div class="col-sm-8">
            <div class="form-group">
                <label for="nome">Modelo:</label>
                <input type="text" class="form-control" id="modelo" name="modelo" value="{{$reg->modelo or old('modelo')}}" @if ($acao==3) readonly="readonly"> @else autofocus> @endif
            </div>
        </div>
    </div>         

    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
              <label for="clube">Marca:</label>
              <input type="text" class="form-control" id="marca" name="marca" value="{{$reg->marca or old('marca')}}" @if ($acao==3) readonly="readonly"
                @endif>
            </div>
        </div>
    </div>    
    
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
              <label for="clube">Categoria:</label>
              <input type="text" class="form-control" id="categoria" name="categoria" value="{{$reg->categoria or old('categoria')}}" @if ($acao==3) readonly="readonly"
                @endif>
            </div>
        </div>
    </div> 

          {{-- <div class="row">
            <div class="col-sm-8">
                <label for="nome">E-mail:</label>
                <input type="text" class="form-control" id="email" name="email" value="{{$reg->email or old('email')}}" @if ($acao==3) readonly="readonly"> @else @endif
            </div>
          </div> --}}
    
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label for="clube">Descrição:</label>
                <input type="text" class="form-control" id="descricao" name="descricao" value="{{$reg->descricao or old('descricao')}}" @if ($acao==3) readonly="readonly"
                @endif>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label for="imagem">Foto:</label>
                <input type="file" class="form-control" id="imagem" name="imagem" @if ($acao==3) readonly="readonly" @endif>
            </div>
        </div>
    </div>
        

        @if ($acao == 1 or $acao == 2)
        <input type="submit" value="Enviar" class="btn btn-danger">
  </form>
  @else
  <div class="text-right">
    <a href="{{ url()->previous() }}" class="btn btn-success btn-sm" role="button">Voltar</a>
  </div>
  @endif
  </div>
  <div class="col-sm-4">
    @if ($acao == 1)
    <img src="" id="outFoto" style="width: 300px; height: 200px; display: none;" alt="Foto"> @else
    <img src="../../storage/{{ $reg->foto }}" id="outFoto" style="width: 300px; height: 200px;" alt="Foto"> @endif
  </div>
</div>

  <!-- arquivos js ficam em public/js -->
  <script src="{{ URL::asset('js/foto.js') }}"></script> @endsection

resources/views/graficos.blade.php
@extends('modelo') 
@section('conteudo')

<div class="row">
  <div class="col-sm-12">
     <h3>Gráficos de Marcas</h3>
  </div>     
</div>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
 google.charts.load("current", {packages:["corechart"]});
 google.charts.setOnLoadCallback(drawChart);

 function drawChart() {
 var data = google.visualization.arrayToDataTable([['Marca', 'Nº Reservas'],
 @foreach ($graficos as $grafico)
 {!! "['$grafico->marca', $grafico->num]," !!}
 @endforeach
 ]);
 var options = {
 title: 'O gráfico abaixo mostra a relação das marcas de instrumentos que estão na preferência dos clientes.',
 is3D: true,
 };
 var chart = new google.visualization
 .PieChart(document.getElementById('piechart_3d'));
 chart.draw(data, options);
 }
</script>
<div id="piechart_3d" style="width: 900px; height: 500px;"></div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/lista_intrumentos.blade.php
@extends('modelo') 
@section('conteudo')

<div class="row">
  <div class="col-sm-10">
     <h3>Instrumentos Cadastrados</h3>
  </div>   
  <div class="col-sm-2">
    <a href="{{ route('produtos.create') }}" class="btn btn-primary btn-sm" style="margin-top:24px" role="button">Cadastro Novo</a>
  </div>   
</div>

@if (session('status'))
<div class="alert alert-success">
  {{ session('status') }}
</div>
@endif

<table class="table table-hover">
  <thead>
    <tr>
      <th>Código</th>
      <th>Modelo</th>
      <th>Marca</th>
      <th>Categoria</th>
      <th>Descrição</th>
      <th>Foto</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>

    @foreach ($linhas as $linha)
    <tr>
      <td> {{ $linha->id}} </td>
      <td> {{ $linha->modelo }} </td>
      <td> {{ $linha->marca }} </td>
      <td> {{ $linha->categoria }} </td>
      <td> {{ $linha->descricao }} </td>
      <td> <img src='../../storage/{{ $linha->foto }}' style='width: 120px; height: 80px;'> </td>
      <td> <a href="{{ route('produtos.edit', $linha->id) }}" class="btn btn-info btn-sm" role="button">Alterar</a>&nbsp;
        <!--  <a href="{{ route('produtos.show', $linha->id) }}" class="btn btn-success btn-sm" role="button">Consultar</a>&nbsp; -->
        <form method="post" action="{{ route('produtos.destroy', $linha->id)}}" style="display: inline-block" onsubmit="return confirm('Confirma Exclusão do Instrumento?')">          
          {{ method_field('delete') }}
          {{ csrf_field() }}
          <input type="submit" class="btn btn-danger btn-sm" value="Excluir">
        </form>
        <!-- <a href="{{ route('produtos.email', $linha->id) }}" class="btn btn-primary btn-sm" role="button">E-mail</a>&nbsp; -->

      </td>
    </tr>
    
    @endforeach

  </tbody>
</table>

{{ $linhas->links() }}
  
 
@endsection

resources/views/modelo.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title>IME</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">IME</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{{ route('produtos.index') }}">Home</a></li>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Cadastros <span class="caret"></span></a>
        <ul class="dropdown-menu">
        <li><a href="{{ route('produtos.index') }}">Produtos</a></li>
        </ul>
      </li>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Estatísticas de Reservas <span class="caret"></span></a>
        <ul class="dropdown-menu">
        <li><a href="{{ route('produtos.dadosReservas') }}">Dados de Reservas</a></li>
        <li><a href="{{ route('produtos.graficos') }}">Gráficos</a></li>
        <li><a href="{{ route('produtos.relatorios') }}">Relatórios</a></li>
        </ul>
      </li>
      
    </ul>
    <ul class="nav navbar-nav navbar-right">
    <li><a href="{{ route('login') }}"><span class="glyphicon glyphicon-user"></span> {{ Auth::user()->name }}</a></li>
      <li>
          <a href="{{ route('logout') }}"
          onclick="event.preventDefault();
                   document.getElementById('logout-form').submit();"><span class="glyphicon glyphicon-log-in"></span>
          Sair
      </a>

      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
          {{ csrf_field() }}
      </form>        
      </li>
    </ul>
  </div>
</nav>
  
<div class="container">

@yield('conteudo')  

</div>

</body>
</html>

resources/views/principal.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title>IME</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
   <div class="container">
        <div class="row">
            <div class="col-sm-10">
                <h1>
                    INSTRUMENTAL MUSICAL EXPERIENCE
                </h1>
            </div>
            <div class="col-sm-2">
                    <a href="{{route('reservas.index')}}"><p style="margin-top:24px">Home</p></a>                     
            </div>
        </div>
        
        <div class="row">
            <div class="col-sm-12">
                <h3>Conheça, teste e aprove antes de comprar!</h3>
            </div>
        </div>
    <form action="{{route('reserva.pesquisa')}}" method="post">
        <div class="row">
            <div class="col-sm-8 input-group">
                    {{ csrf_field() }}
                    <input type="text" class="form-control" id="busca" name="busca" placeholder="Ache o instrumento que procura">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">OK</button>
                    </span>
                </div>
            </div>
    </form>
        <div class="container">
            
            @yield('pagina')
        </div>
        
   </div>
   
</body>
</html>

resources/views/relatorios.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title>IME</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<body>

<div class="container-fluid">
    <h4 style="text-align: center">INSTRUMENTAL MUSICAL EXPERIENCE</h4>
    <h5 style="text-align: center">Relatório de Instrumentos Cadastrados no Sistema</h5>
    <table class="table table-striped table-sm">
        <thead class="thead-light">
            <tr>
                <th>Modelo</th>
                <th>Marca</th>
                <th>Categoria</th>
                <th>Imagem</th>
            </tr>
        </thead>
        <tbody>
            @foreach($produtos as $produto)
            <tr>
                <td>{{$produto->modelo}}</td>
                <td>{{$produto->marca}}</td>
                <td>{{$produto->categoria}}</td>
                <td style="text-align: center">
                        <img src="{{public_path('storage/'.$produto->foto)}}" style="width:100px;height:60px">
                {{-- @if (Storage::exists($candidata->foto))
                    
                @else 
                    <img style="width: 100px" src="{{public_path('storage/fotos/semfoto.jpeg')}}">
                @endif --}}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
    
</body>

</html>